package mapeo;
// Generated 28-nov-2016 21:21:01 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cocheras generated by hbm2java
 */
public class Cocheras  implements java.io.Serializable {


     private int codCochera;
     private int capacidad;
     private Set treneses = new HashSet(0);

    public Cocheras() {
    }

	
    public Cocheras(int codCochera, int capacidad) {
        this.codCochera = codCochera;
        this.capacidad = capacidad;
    }
    public Cocheras(int codCochera, int capacidad, Set treneses) {
       this.codCochera = codCochera;
       this.capacidad = capacidad;
       this.treneses = treneses;
    }
   
    public int getCodCochera() {
        return this.codCochera;
    }
    
    public void setCodCochera(int codCochera) {
        this.codCochera = codCochera;
    }
    public int getCapacidad() {
        return this.capacidad;
    }
    
    public void setCapacidad(int capacidad) {
        this.capacidad = capacidad;
    }
    public Set getTreneses() {
        return this.treneses;
    }
    
    public void setTreneses(Set treneses) {
        this.treneses = treneses;
    }




}


