package mapeo;
// Generated 28-nov-2016 21:21:01 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Lineas generated by hbm2java
 */
public class Lineas  implements java.io.Serializable {


     private int codLinea;
     private String tipo;
     private double longitud;
     private Set treneses = new HashSet(0);
     private Set lineaEstacions = new HashSet(0);

    public Lineas() {
    }

	
    public Lineas(int codLinea, String tipo, double longitud) {
        this.codLinea = codLinea;
        this.tipo = tipo;
        this.longitud = longitud;
    }
    public Lineas(int codLinea, String tipo, double longitud, Set treneses, Set lineaEstacions) {
       this.codLinea = codLinea;
       this.tipo = tipo;
       this.longitud = longitud;
       this.treneses = treneses;
       this.lineaEstacions = lineaEstacions;
    }
   
    public int getCodLinea() {
        return this.codLinea;
    }
    
    public void setCodLinea(int codLinea) {
        this.codLinea = codLinea;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public double getLongitud() {
        return this.longitud;
    }
    
    public void setLongitud(double longitud) {
        this.longitud = longitud;
    }
    public Set getTreneses() {
        return this.treneses;
    }
    
    public void setTreneses(Set treneses) {
        this.treneses = treneses;
    }
    public Set getLineaEstacions() {
        return this.lineaEstacions;
    }
    
    public void setLineaEstacions(Set lineaEstacions) {
        this.lineaEstacions = lineaEstacions;
    }




}


