package mapeo;
// Generated 28-nov-2016 21:21:01 by Hibernate Tools 4.3.1



/**
 * Viajes generated by hbm2java
 */
public class Viajes  implements java.io.Serializable {


     private Integer codViaje;
     private Estaciones estacionesByEstacionprocedencia;
     private Estaciones estacionesByEstaciondestino;

    public Viajes() {
    }

    public Viajes(Estaciones estacionesByEstacionprocedencia, Estaciones estacionesByEstaciondestino) {
       this.estacionesByEstacionprocedencia = estacionesByEstacionprocedencia;
       this.estacionesByEstaciondestino = estacionesByEstaciondestino;
    }
   
    public Integer getCodViaje() {
        return this.codViaje;
    }
    
    public void setCodViaje(Integer codViaje) {
        this.codViaje = codViaje;
    }
    public Estaciones getEstacionesByEstacionprocedencia() {
        return this.estacionesByEstacionprocedencia;
    }
    
    public void setEstacionesByEstacionprocedencia(Estaciones estacionesByEstacionprocedencia) {
        this.estacionesByEstacionprocedencia = estacionesByEstacionprocedencia;
    }
    public Estaciones getEstacionesByEstaciondestino() {
        return this.estacionesByEstaciondestino;
    }
    
    public void setEstacionesByEstaciondestino(Estaciones estacionesByEstaciondestino) {
        this.estacionesByEstaciondestino = estacionesByEstaciondestino;
    }




}


