package modelo;
// Generated 28-nov-2016 13:35:22 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Estaciones generated by hbm2java
 */
public class Estaciones  implements java.io.Serializable {


     private int codEstacion;
     private Accesos accesos;
     private String nombre;
     private String localidad;
     private String direccion;
     private int contacto;
     private Set viajesesForEstacionprocedencia = new HashSet(0);
     private Set lineaEstacions = new HashSet(0);
     private Set viajesesForEstaciondestino = new HashSet(0);

    public Estaciones() {
    }

	
    public Estaciones(int codEstacion, Accesos accesos, String nombre, String localidad, String direccion, int contacto) {
        this.codEstacion = codEstacion;
        this.accesos = accesos;
        this.nombre = nombre;
        this.localidad = localidad;
        this.direccion = direccion;
        this.contacto = contacto;
    }
    public Estaciones(int codEstacion, Accesos accesos, String nombre, String localidad, String direccion, int contacto, Set viajesesForEstacionprocedencia, Set lineaEstacions, Set viajesesForEstaciondestino) {
       this.codEstacion = codEstacion;
       this.accesos = accesos;
       this.nombre = nombre;
       this.localidad = localidad;
       this.direccion = direccion;
       this.contacto = contacto;
       this.viajesesForEstacionprocedencia = viajesesForEstacionprocedencia;
       this.lineaEstacions = lineaEstacions;
       this.viajesesForEstaciondestino = viajesesForEstaciondestino;
    }
   
    public int getCodEstacion() {
        return this.codEstacion;
    }
    
    public void setCodEstacion(int codEstacion) {
        this.codEstacion = codEstacion;
    }
    public Accesos getAccesos() {
        return this.accesos;
    }
    
    public void setAccesos(Accesos accesos) {
        this.accesos = accesos;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getLocalidad() {
        return this.localidad;
    }
    
    public void setLocalidad(String localidad) {
        this.localidad = localidad;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public int getContacto() {
        return this.contacto;
    }
    
    public void setContacto(int contacto) {
        this.contacto = contacto;
    }
    public Set getViajesesForEstacionprocedencia() {
        return this.viajesesForEstacionprocedencia;
    }
    
    public void setViajesesForEstacionprocedencia(Set viajesesForEstacionprocedencia) {
        this.viajesesForEstacionprocedencia = viajesesForEstacionprocedencia;
    }
    public Set getLineaEstacions() {
        return this.lineaEstacions;
    }
    
    public void setLineaEstacions(Set lineaEstacions) {
        this.lineaEstacions = lineaEstacions;
    }
    public Set getViajesesForEstaciondestino() {
        return this.viajesesForEstaciondestino;
    }
    
    public void setViajesesForEstaciondestino(Set viajesesForEstaciondestino) {
        this.viajesesForEstaciondestino = viajesesForEstaciondestino;
    }




}


