package modelo;
// Generated 28-nov-2016 13:35:22 by Hibernate Tools 4.3.1



/**
 * LineaEstacion generated by hbm2java
 */
public class LineaEstacion  implements java.io.Serializable {


     private LineaEstacionId id;
     private Estaciones estaciones;
     private Lineas lineas;
     private String estado;

    public LineaEstacion() {
    }

    public LineaEstacion(LineaEstacionId id, Estaciones estaciones, Lineas lineas, String estado) {
       this.id = id;
       this.estaciones = estaciones;
       this.lineas = lineas;
       this.estado = estado;
    }
   
    public LineaEstacionId getId() {
        return this.id;
    }
    
    public void setId(LineaEstacionId id) {
        this.id = id;
    }
    public Estaciones getEstaciones() {
        return this.estaciones;
    }
    
    public void setEstaciones(Estaciones estaciones) {
        this.estaciones = estaciones;
    }
    public Lineas getLineas() {
        return this.lineas;
    }
    
    public void setLineas(Lineas lineas) {
        this.lineas = lineas;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


