package modelo;
// Generated 28-nov-2016 13:35:22 by Hibernate Tools 4.3.1



/**
 * LineaEstacionId generated by hbm2java
 */
public class LineaEstacionId  implements java.io.Serializable {


     private int codEstacion;
     private int codLinea;

    public LineaEstacionId() {
    }

    public LineaEstacionId(int codEstacion, int codLinea) {
       this.codEstacion = codEstacion;
       this.codLinea = codLinea;
    }
   
    public int getCodEstacion() {
        return this.codEstacion;
    }
    
    public void setCodEstacion(int codEstacion) {
        this.codEstacion = codEstacion;
    }
    public int getCodLinea() {
        return this.codLinea;
    }
    
    public void setCodLinea(int codLinea) {
        this.codLinea = codLinea;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LineaEstacionId) ) return false;
		 LineaEstacionId castOther = ( LineaEstacionId ) other; 
         
		 return (this.getCodEstacion()==castOther.getCodEstacion())
 && (this.getCodLinea()==castOther.getCodLinea());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCodEstacion();
         result = 37 * result + this.getCodLinea();
         return result;
   }   


}


