package modelo;
// Generated 28-nov-2016 13:35:22 by Hibernate Tools 4.3.1



/**
 * Trenes generated by hbm2java
 */
public class Trenes  implements java.io.Serializable {


     private Integer codTren;
     private Cocheras cocheras;
     private Lineas lineas;
     private String compañia;
     private String tipo;
     private String modelo;
     private String estado;

    public Trenes() {
    }

    public Trenes(Cocheras cocheras, Lineas lineas, String compañia, String tipo, String modelo, String estado) {
       this.cocheras = cocheras;
       this.lineas = lineas;
       this.compañia = compañia;
       this.tipo = tipo;
       this.modelo = modelo;
       this.estado = estado;
    }
   
    public Integer getCodTren() {
        return this.codTren;
    }
    
    public void setCodTren(Integer codTren) {
        this.codTren = codTren;
    }
    public Cocheras getCocheras() {
        return this.cocheras;
    }
    
    public void setCocheras(Cocheras cocheras) {
        this.cocheras = cocheras;
    }
    public Lineas getLineas() {
        return this.lineas;
    }
    
    public void setLineas(Lineas lineas) {
        this.lineas = lineas;
    }
    public String getCompañia() {
        return this.compañia;
    }
    
    public void setCompañia(String compañia) {
        this.compañia = compañia;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getModelo() {
        return this.modelo;
    }
    
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


